name: Linting and Tests

on:
  pull_request:
    branches-ignore: main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn
      - name: Install Dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Lint Check
        id: lint
        run: yarn lint
        continue-on-error: true
      - name: Test
        id: test
        run: yarn test
        continue-on-error: true
      - name: Report Failures
        if: ${{ steps.lint.outcome == 'failed' || steps.test.outcome == 'failed' }}
        run: |
          echo 'One or more steps failed, check output above and resolve.'
          exit 1
      - name: Report Success
        run: |
          echo 'Everything passed'
          exit 0