name: Linting and Tests

on: pull_request

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn
      - name: Install Dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Lint Check
        id: lint
        run: yarn lint
        continue-on-error: true
      - name: Test
        id: test
        run: yarn test
        continue-on-error: true
      - name: Report Outcomes
        run: |
          echo 'linter outcome was ${{ steps.lint.outcome }}'
          echo 'test outcome was ${{ steps.test.outcome }}'
          if [ "${{ steps.lint.outcome }}" = "failure" ] || [ "${{ steps.test.outcome }}" = "failure" ]; \
            then echo 'One or more steps failed, check output above and resolve.'; exit 1; fi